=== Aresh-P/tapp/tapp/overview/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [ "meetings", "services", "events", "toys", "links" ],
  "properties": {
    "meetings": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "name", "location", "day", "time" ],
        "properties": {
          "name": { "type": "string" },
          "location": { "type": "string" },
          "day": { "type": "string" },
          "time": { "$ref": "#/definitions/hmTime" }
        }
      }
    },
    "services": {
      "type": "array",
      "minItems": 1,
      "items": { "type": "string" }
    },
    "events": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "name", "blurb", "when" ],
        "properties": {
          "name": { "type": "string" },
          "blurb": { "type": "string" },
          "when": { "type": "string" }
        }
      }
    },
    "toys": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "name", "blurb" ],
        "properties": {
          "name": { "type": "string" },
          "blurb": { "type": "string" }
        }
      }
    },
    "links": {
      "type": "array",
      "minItems": 1,
      "items": { "type": "string" }
    }
  },
  "definitions": {
    "isoDate": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-1][0-9]-[0-3][0-9]$"
    },
    "hmTime": {
      "type": "string",
      "pattern": "^[0-2][0-9]:[0-5][0-9]$"
    },
    "url": {
      "type": "string",
      "pattern": "(https?|ftp)://([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?"
    },
    "unixFile": {
      "type": "string",
      "pattern": "(/[^\\s]+)*[^\\s]*(.[^\\s]*)*.?[^\\s]+"
    }
  }
}

=== Aresh-P/tapp/data/2016-09_F16-flyer.json
{
  "meetings" : [
    {
      "name" : "Machine Room",
      "location" : "Cyert B6",
      "day" : "Saturday",
      "time" : "17:00"
    },
    {
      "name" : "Admin Mtg",
      "location" : "Wean 5304",
      "day" : "Tuesday",
      "time" : "17:00"
    }
  ],
  "services" : [
    "Contributed Webserver",
    "OpenVMS Cluster",
    "Open Source Project Mirrors",
    "Realtime Graphics Demos",
    "Open-Access Virtual Machines",
    "Jabber Chat Server"
  ],
  "events" : [
    {
      "name" : "Demosplash",
      "blurb" : "The largest demoparty on the East Coast",
      "when" : "Nov 4-5"
    },
    {
      "name" : "Retro Gaming Night",
      "blurb" : "Classic games on original hardware",
      "when" : "Spring"
    },
    {
      "name" : "Talk Series",
      "blurb" : "Unlock the full power of your system",
      "when" : "All Year"
    }
  ],
  "toys" : [
    {
      "name" : "Shell Machines",
      "blurb" : "Less crowded than Andrew and no nightly reboots."
    },
    {
      "name" : "Unusual Hardware",
      "blurb" : "Ancient, modern, or just plain weird?  We have it."
    },
    {
      "name" : "Virtual Machines",
      "blurb" : "Why pay someone else to host your code?"
    }
  ],
  "links" : [
    "cmucc.org",
    "twitter.com/cl0x",
    "facebook.com/cmucclub",
    "irc://freenode.net/##cclub"
  ]
}

=== Aresh-P/tapp/data/2014-01_S14-flyer.json
{
  "meetings" : [
    {
      "name" : "Machine Room",
      "location" : "Cyert B6",
      "day" : "Saturday",
      "time" : "17:00"
    },
    {
      "name" : "Admin Mtg",
      "location" : "Porter A19C",
      "day" : "Tuesday",
      "time" : "17:30"
    }
  ],
  "services" : [
    "Contributed Webserver",
    "OpenVMS Cluster",
    "Open Source Project Mirrors",
    "Realtime Graphics Demos",
    "Freenode IRC Server",
    "Jabber &amp; Zephyr Chat Servers"
  ],
  "events" : [
    {
      "name" : "Demosplash",
      "blurb" : "North America's largest Fall demoparty",
      "when" : "October"
    },
    {
      "name" : "Retro Gaming Night",
      "blurb" : "Classic games on original hardware",
      "when" : "Spring"
    },
    {
      "name" : "Talk Series",
      "blurb" : "Unlock the full power of your systems",
      "when" : "All Year"
    }
  ],
  "toys" : [
    {
      "name" : "Shell Machines",
      "blurb" : "Less crowded than Andrew and no nightly reboots."
    },
    {
      "name" : "Club AFS",
      "blurb" : "More space and faster access than Andrew AFS."
    },
    {
      "name" : "Virtual Machines",
      "blurb" : "Why pay someone else to host your code?"
    }
  ],
  "links" : [
    "cmucc.org",
    "twitter.com/cl0x",
    "facebook.com/cmucclub",
    "irc://freenode.net/##cclub"
  ]
}
