=== Aresh-P/tapp/tapp/talks/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [ "name", "slug", "first_date", "start_time", "end_time", "location",
    "ical_desc", "web_desc", "web_suggest", "talks", "url", "sponsor" ],
  "properties": {
    "name": { "type": "string" },
    "slug": { "type": "string" },
    "first_date": { "$ref": "#/definitions/isoDate" },
    "start_time": { "$ref": "#/definitions/hmTime" },
    "end_time": { "$ref": "#/definitions/hmTime" },
    "location": { "type": "string" },
    "ical_desc": { "type": "string" },
    "web_desc": { "type": "string" },
    "web_suggest": { "type": "string" },
    "categories": {
      "type": "array",
      "minItems": 0,
      "items": { "type": "string" },
      "uniqueItems": true
    },
    "talks": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "title", "cat", "desc" ],
        "properties": {
          "title": { "type": "string" },
          "cat": {
            "type": "integer",
            "minimum": 0
           },
          "desc": { "type": "string" },
          "location": { "type": "string" }
        }
      }
    },
    "url": { "$ref": "#/definitions/url" },
    "sponsor": {
      "type": "object",
      "required": [ "name", "url", "desc", "logo", "logo_svg-gen_height_offset" ],
      "properties": {
        "name": { "type": "string" },
        "url": { "$ref": "#/definitions/url" },
        "desc": { "type": "string" },
        "logo": { "$ref": "#/definitions/unixFile" },
        "logo_svg-gen_height_offset": { "type": "integer" }
      }
    }
  },
  "definitions": {
    "isoDate": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-1][0-9]-[0-3][0-9]$"
    },
    "hmTime": {
      "type": "string",
      "pattern": "^[0-2][0-9]:[0-5][0-9]$"
    },
    "url": {
      "type": "string",
      "pattern": "(https?|ftp)://([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?"
    },
    "unixFile": {
      "type": "string",
      "pattern": "(/[^\\s]+)*[^\\s]*(.[^\\s]*)*.?[^\\s]+"
    }
  }
}

=== Aresh-P/tapp/data/2015-04_F15-talks-part2.json
{
  "name" : "Fall 2015",
  "slug" : "fall15",
  "first_date" : "2014-08-26",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Gates 4301",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>This year, we're talking about kitties!</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to operations@club.</p>",
  "categories" : [
    "Power Tools",
    "Retro",
    "The Power of Linux",
    "Bash Some Heads",
    "It's Dangerous to Go Alone, Take This"
  ],
  "talks" : [
    {
      "title" : "Linux Containers",
      "cat" : 3,
      "notes" : "containers.html",
      "desc" : "The new containerization technologies available in Linux are receiving a massive amount of hype. Learn why everyone's excited about Docker, and how you can use it yourself."
    },
    {
      "title" : "Advanced Bash",
      "cat" : 4,
      "notes" : "advbash.html",
      "desc" : "Most developers and sysadmins and devops spend a lot of time on the command line. Learn how to maximize your effectiveness with bash - it's got all the cool features you need!"
    },
    {
      "title" : "Bash Scripting",
      "cat" : 4,
      "notes" : "bashscript.html",
      "desc" : "Bash scripting is the classic sysadmin technique, but it's useful for developers and even casual users. Automate your computer and write simple yet powerful and useful programs, with bash scripting."
    },
    {
      "title" : "Debugging",
      "cat" : 5,
      "notes" : "debugging.html",
      "desc" : "Learn the best techniques for expunging those pesky bugs from your programs!"
    },
    {
      "title" : "System Exploitation",
      "cat" : 5,
      "notes" : "exploitation.html",
      "desc" : "Get a tutorial in how bad people and security researchers break your web app and make your life harder!"
    },
    {
      "title" : "(Thanksgiving Break)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "PGP and Cryptography",
      "cat" : 5,
      "notes" : "crypto.html",
      "desc" : "Learn to create a PGP private/public keypair and use it for encryption and identity verification."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "2013logo_light.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/fall2014/talk_series.json
{
  "name" : "Fall 2014",
  "slug" : "fall14",
  "first_date" : "2014-08-27",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Wean Hall 5415",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>DEVOPS!  Hippest of buzzwords, earner of thousands!  Learn to harness the immense power of devops for yourself, by coming to the Fall 2014 Computer Club Workshop/Talk Series.  We will tell you the tricks that will allow you to transcend the annoyances of administration and offenses of operations, and return to the elegant, pure simplicity of raw code!</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to operations@club.</p>",
  "categories" : [
    "Power Tools",
    "Retro",
    "The Power of Linux",
    "Bash Some Heads",
    "It's Dangerous to Go Alone, Take This"
  ],
  "talks" : [
    {
      "title" : "Power Computing at CMU",
      "cat" : 1,
      "notes" : "power-computing.html",
      "desc" : "CMU is the top computer science university in the world. So obviously there are some useful software tools here, available to you! Learn what they are and how to use them to get your work done faster and more efficiently."
    },
    {
      "title" : "Power Vim",
      "cat" : 1,
      "notes" : "power-vim.html",
      "desc" : "Attend this talk to learn how to efficiently use the most powerful editor on earth! Even if you use an inferior editor, come to this talk! You might find you'd prefer this one!"
    },
    {
      "title" : "Power Emacs",
      "cat" : 1,
      "notes" : "power-emacs.html",
      "desc" : "Attend this talk to learn how to efficiently use the most powerful editor on earth! Even if you use an inferior editor, come to this talk! You might find you'd prefer this one!"
    },
    {
      "title" : "Source Version Control with Git",
      "cat" : 1,
      "notes" : "power-git.html",
      "desc" : "Do you like having undo and redo available in your editor? Then you're sure to like having undo and redo available on the command line! In this talk, you'll learn about the ideas behind the source version control system Git, and how to use its immense power for your own aims."
    },
    {
      "title" : "Retro Platforms Overview",
      "cat" : 2,
      "notes" : "retro.html",
      "desc" : "Why do you still get asked to keep lines of code to 80 columns or less? What's that 'Terminal' thing on your Mac and why should you care? Is that funny looking 80s computer your parents have sitting in the garage worth messing with? Attend this talk for a crash course in the history of computing that will answer these questions and more!"
    },
    {
      "title" : "Installing Linux Workshop",
      "cat" : 3,
      "notes" : "linux.html",
      "desc" : "We'll walk you through installing Linux and getting started with it, both on your own hardware or a virtual machine. Come get access to the best, most direct development environment possible!"
    },
    {
      "title" : "Advanced Filesystems and RAID",
      "cat" : 3,
      "notes" : "filesystems.html",
      "desc" : "Learn about exciting new developments like btrfs, and the fantastic features they provide! Also a short segment about things like LVM and RAID."
    },
    {
      "title" : "System Management with systemd",
      "cat" : 3,
      "notes" : "systemd.html",
      "desc" : "systemd is the much-maligned project that is either upgrading or ruining the core of Linux, depending on who you ask. Learn in this talk about the exciting features systemd brings, and why there's no need to fear Lennart Poettering!"
    },
    {
      "title" : "Linux Containers",
      "cat" : 3,
      "notes" : "containers.html",
      "desc" : "The new containerization technologies available in Linux are receiving a massive amount of hype. Learn why everyone's excited about Docker, and how you can use it yourself."
    },
    {
      "title" : "Advanced Bash",
      "cat" : 4,
      "notes" : "advbash.html",
      "desc" : "Most developers and sysadmins and devops spend a lot of time on the command line. Learn how to maximize your effectiveness with bash - it's got all the cool features you need!"
    },
    {
      "title" : "Bash Scripting",
      "cat" : 4,
      "notes" : "bashscript.html",
      "desc" : "Bash scripting is the classic sysadmin technique, but it's useful for developers and even casual users. Automate your computer and write simple yet powerful and useful programs, with bash scripting."
    },
    {
      "title" : "Debugging",
      "cat" : 5,
      "notes" : "debugging.html",
      "desc" : "Learn the best techniques for expunging those pesky bugs from your programs!"
    },
    {
      "title" : "System Exploitation",
      "cat" : 5,
      "notes" : "exploitation.html",
      "desc" : "Get a tutorial in how bad people and security researchers break your web app and make your life harder!"
    },
    {
      "title" : "(Thanksgiving Break)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "PGP and Cryptography",
      "cat" : 5,
      "notes" : "crypto.html",
      "desc" : "Learn to create a PGP private/public keypair and use it for encryption and identity verification."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compiles, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "2013logo_light.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2015-03_S15-talks-part2.json
{
  "name" : "Spring 2015",
  "slug" : "spring15",
  "first_date" : "2015-03-18",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Gates 4301",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>Want to learn more about practical aspects of computer engineering, ranging from command line usage to webapp deployment? Come to Computer Club's Spring 2015 weekly talk series! This semester, we will discuss topics ranging from command line workflows to Node.js.  <b>More talks will be added soon!</b></p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to operations@club.</p>",
  "categories" : [
    "Programming Languages"
  ],
  "talks" : [
    {
      "title" : "C++: A less bad systems language",
      "cat" : 4,
      "notes" : "cplusplus.pdf",
      "desc" : "Do you need the performance and control of C but also want convenient features such as type safety, a well-developed standard library, and tools to enable better memory safety? In this talk, we will go over the basics of C++ and discuss design patterns and idioms, such as Resource Acquisition is Initialization, which can be used to develop robust, performant, and elegant code. We will also cover some of the new features in C++11 such as lambdas and move semantics."
    },
    {
      "title" : "Real-Time Operating Systems",
      "cat" : 4,
      "notes" : "realtime-os.html",
      "desc" : "Join Mark Wagner, an Engineering Director at Green Hills Software, for an interactive discussion about examples of complex embedded systems, the safety and security interactions of the components in these systems, and the ways real-time operating systems can secure the interactions."
    },
    {
      "title" : "(SigBovik)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "Haskell: Safe, powerful abstractions",
      "cat" : 4,
      "notes" : "haskell.html",
      "desc" : "Haskell is a functional programming language designed to make it quick and easy to write correct high-level code.  In this talk, we will discuss some common misconceptions about Haskell, introduce basic syntax and semantics, and give a brief, practically-oriented introduction to monads."
    },
    {
      "title" : "sed &amp; awk: &#8217;70s tools still hip today",
      "cat" : 4,
      "notes" : "sed-awk.html",
      "desc" : "Providing much of the meat and bones of shell scripting, sed and awk process line-based data into more useful information.  This talk will convey how to use these classic tools from the early days of UNIX to do what you need, and how they have influenced other languages."
    },
    {
      "title" : "Verilog &amp; FPGAs: Coding hardware",
      "cat" : 4,
      "notes" : "verilog.html",
      "desc" : "Ever hear people talking about Verilog or VHDL, and wonder how on earth you can write code that becomes hardware?  Attend this talk to learn about hardware description languages and how programmable logic works!"
    },
    {
      "title" : "Clojure: An elegant weapon",
      "cat" : 4,
      "notes" : "clojure.html",
      "desc" : "Clojure is a functional programming language designed for concurrency.  It is a dialect of Lisp, and it runs on the JVM.  It has an awesome REPL-driven workflow.  It makes it trivially easy to use Java libraries and programs in a language that doesn't suck.  It is the most popular alternative to using Java on the JVM.  It is basically the best thing ever.  Want to learn more?  Come to this talk."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "logos/sponsors/green-hills/GHS_Logo.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/spring2015/s15_talks_part1.json
{
  "name" : "Spring 2015",
  "slug" : "spring15",
  "first_date" : "2015-01-21",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Wean Hall 5415",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>...</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to operations@club.</p>",
  "categories" : [
    "A...",
    "B...",
    "C...",
    "D..."
  ],
  "talks" : [
    {
      "title" : "Useful Command Line Workflows",
      "cat" : 1,
      "notes" : "command-line.html",
      "desc" : "..."
    },
    {
      "title" : "Elliptic Curve Cryptography",
      "cat" : 2,
      "notes" : "elliptic-curve-crypto.html",
      "desc" : "..."
    },
    {
      "title" : "Introduction to Bitcoin",
      "cat" : 2,
      "notes" : "bitcoin.html",
      "desc" : "..."
    },
    {
      "title" : "Node.js 101",
      "cat" : 3,
      "notes" : "node-js.html",
      "desc" : "..."
    },
    {
      "title" : "Docker and Fig for Web Applications",
      "cat" : 3,
      "notes" : "docker-and-fig.html",
      "desc" : "..."
    },
    {
      "title" : "Vim as an IDE",
      "cat" : 4,
      "notes" : "vim.html",
      "desc" : "..."
    },
    {
      "title" : "Coffeescript 101",
      "cat" : 4,
      "notes" : "coffeescript.html",
      "desc" : "..."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "2013logo_light.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2016-01_S16-talks.json
{
  "name" : "Spring 2016",
  "slug" : "spring16",
  "first_date" : "2016-01-20",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Wean 5421",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>Have you ever wondered how fast inverse square root works, wanted to learn a bit of computing history, or craved the thrill of learning a new language again, but didn't know where to start looking? Look no further! Whether you're a hacking veteran or a newfound computer lover, there's something for you in Computer Club's Spring 2016 weekly talk series, so swing on by!</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to talks@club.</p>",
  "categories" : [
    "Computing Basics",
    "Computing History",
    "Privacy and Security",
    "Creative Computing",
    "Languages",
    "Awesome Hackery"
  ],
  "talks" : [
    {
      "title" : "Useful Command Line Workflows",
      "cat" : 1,
      "notes" : "command-line.html",
      "desc" : ""
    },
    {
      "title" : "The Dot Com Bubble",
      "cat" : 2,
      "notes" : "dot-com-bubble.html",
      "desc" : ""
    },
    {
      "title" : "Introducing the X68000: Japan's 16-bit Beast",
      "cat" : 2,
      "notes" : "x68000.html",
      "desc" : ""
    },
    {
      "title" : "PGP and Public Key Cryptography",
      "cat" : 3,
      "notes" : "pgp.html",
      "desc" : ""
    },
    {
      "title" : "Privacy Technology and You",
      "cat" : 3,
      "notes" : "privacy-tech.html",
      "desc" : ""
    },
    {
      "title" : "Authoring Text Adventures",
      "cat" : 4,
      "notes" : "text-adventures.html",
      "desc" : ""
    },
    {
      "title" : "What is AI and Why Should I Care?",
      "cat" : 4,
      "notes" : "ai-intro.html",
      "desc" : ""
    },
    {
      "title" : "(Spring Break)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "Haskell for SML Programmers",
      "cat" : 5,
      "notes" : "haskell.html",
      "desc" : ""
    },
    {
      "title" : "COBOL: 57 Years Old and Still Punching (Cards)",
      "cat" : 5,
      "notes" : "cobol.html",
      "desc" : ""
    },
    {
      "title" : "Customization and Programming in Emacs Lisp",
      "cat" : 5,
      "notes" : "emacs-lisp.html",
      "desc" : ""
    },
    {
      "title" : "Build a JIT Compiler in 60 Minutes",
      "cat" : 5,
      "notes" : "jit-compiler.html",
      "desc" : ""
    },
    {
      "title" : "Introduction to Linux Kernel Hacking",
      "cat" : 6,
      "notes" : "kernel-hacking.html",
      "desc" : ""
    },
    {
      "title" : "CoffeeScript => WebGL Solar Systems!",
      "cat" : 6,
      "notes" : "coffeescript.html",
      "desc" : ""
    },
    {
      "title" : "\"What the 0x5f3759df?!\" Float Hacking",
      "cat" : 6,
      "notes" : "float-hacking.html",
      "desc" : ""
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "assets/ghs_logo.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2018-02_S18-talks.json
{
 "name" : "Spring 2018",
 "slug" : "spring18",
 "first_date" : "2018-02-07",
 "start_time" : "20:00",
 "end_time" : "21:00",
 "location" : "Wean 5415",
 "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
 "web_desc" : "<p>DEVOPS! Hippest of buzzwords, earner of thousands! Learn to harness the immense power of devops for yourself, by coming to the Spring 2018 Computer Club Workshop/Talk Series. We will tell you the tricks that will allow you to transcend the annoyances of administration and offenses of operations, and return to the elegant, pure simplicity of raw code!</p>",
 "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to talks@club.</p>",
 "talks" : [
  {
   "title" : "Virtualization in Theory",
   "cat" : 1,
   "notes" : "virt-theory.html",
   "desc" : "Virtual Machines are an increasingly popular way to divide up physical machines, but what's really going on under the hood? We'll take a look at the history of virtualization, different strategies, as well as the hardware that makes efficient virtualization possible."
  },
  {
   "title" : "",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "Virtualization in Practice",
   "cat" : 1,
   "notes" : "virt-practice.html",
   "desc" : "Okay, so you actually want to know how we do virtualization in the real world. This talk will explore some common pieces of software for virtualizing physical machines, and explain some of the benefits and drawbacks of the different options available."
  },
  {
   "title" : "",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "Cryptocurrency",
   "cat" : 2,
   "notes" : "cryptocurrency.html",
   "desc" : "With cryptocurrencies making mainstream news, you might be wondering how it all works. We'll be covering what cryptocurrencies are, how they work, and what has been keeping them in the headlines for the last few months."
  },
  {
   "title" : "",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "GPGPU Programming",
   "cat" : 2,
   "notes" : "gpgpu.html",
   "desc" : "FPGAs are revolutionizing the computing industry by allowing logic designers to reconfigure circuitry on the fly, allowing for rapid development of new hardware where an ASIC would be prohibitively costly or impractical. But how does it all work? Can software-like code be used to design hardware?"
  },
  {
   "title" : "Reconfigurable Logic",
   "cat" : 2,
   "notes" : "reconfigurable-logic.html",
   "desc" : "GPUs are becoming an increasingly popular target for programmers looking to squeeze extra power out of their computers. Attend this talk to see how GPGPU (General-Purpose Computing on Graphics Processing Units) programming allows computationally heavy tasks to be mapped onto hardware originally designed for drawing triangles."
  },
  {
   "title" : "Meltdown, Spectre, and Microarchitecture",
   "cat" : 3,
   "notes" : "meltdown-spectre.html",
   "desc" : "Early this year, two massive hardware vulnerabilities shook the world of computer security. This talk will explore the modern microarchitectural quirks that allowed these attacks to work, as well as the various workarounds and mitigations for these attacks (and any others that might occur between the time of printing of this poster and the talk)."
  },
  {
   "title" : "Designing Safety and Security into Life-Critical Systems",
   "cat" : 3,
   "notes" : "life-critical.html",
   "desc" : "What do you get when you combine a car with a computer? A computer that can cause life-threatening problems! Modern vehicles are massively complex computing platforms, with nearly one hundred processors and over a million lines of code. The complexity is only growing, especially as car manufacturers rush to add \"app stores\" to their dashboards and allow the owner to download potentially buggy software from the internet!  How do you design a system to protect the people inside (and outside) from harm while still allowing user-downloaded content? It starts with designing a Real-Time Operating System (RTOS) that can guarantee separation of important safety-critical code from code that cannot be verified or trusted.  In this tech talk, we'll discuss dealing with the complexity of mixed-criticality systems through strict separation of execution time, memory-space, and resources."
  },
  {
   "title" : "",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "Esoteric Programming Languages",
   "cat" : 3,
   "notes" : "esoteric.html",
   "desc" : "Brainf**k, Whitespace, and Malbolge are just three of the many esoteric programming languages people have designed in an ever-increasing struggle to create the most obtuse, user-unfriendly language possible. We'll showcase a few of these intentionally confusing languages, and share some advice for actually writing code in them."
  }
 ],
 "url" : "http://www.cmucc.org/talks",
 "sponsor" : {
  "name" : "Green Hills Software",
  "url" : "http://www.ghs.com",
  "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
  "logo" : "assets/ghs_logo.svg",
  "logo_svg-gen_height_offset" : 48
 }
}
