=== Aresh-P/tapp/tapp/talks/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [ "name", "slug", "first_date", "start_time", "end_time", "location",
    "ical_desc", "web_desc", "web_suggest", "talks", "url", "sponsor" ],
  "properties": {
    "name": { "type": "string" },
    "slug": { "type": "string" },
    "first_date": { "$ref": "#/definitions/isoDate" },
    "start_time": { "$ref": "#/definitions/hmTime" },
    "end_time": { "$ref": "#/definitions/hmTime" },
    "location": { "type": "string" },
    "ical_desc": { "type": "string" },
    "web_desc": { "type": "string" },
    "web_suggest": { "type": "string" },
    "categories": {
      "type": "array",
      "minItems": 0,
      "items": { "type": "string" },
      "uniqueItems": true
    },
    "talks": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [ "title", "cat", "desc" ],
        "properties": {
          "title": { "type": "string" },
          "cat": {
            "type": "integer",
            "minimum": 0
           },
          "desc": { "type": "string" },
          "location": { "type": "string" }
        }
      }
    },
    "url": { "$ref": "#/definitions/url" },
    "sponsor": {
      "type": "object",
      "required": [ "name", "url", "desc", "logo", "logo_svg-gen_height_offset" ],
      "properties": {
        "name": { "type": "string" },
        "url": { "$ref": "#/definitions/url" },
        "desc": { "type": "string" },
        "logo": { "$ref": "#/definitions/unixFile" },
        "logo_svg-gen_height_offset": { "type": "integer" }
      }
    }
  },
  "definitions": {
    "isoDate": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-1][0-9]-[0-3][0-9]$"
    },
    "hmTime": {
      "type": "string",
      "pattern": "^[0-2][0-9]:[0-5][0-9]$"
    },
    "url": {
      "type": "string",
      "pattern": "(https?|ftp)://([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?"
    },
    "unixFile": {
      "type": "string",
      "pattern": "(/[^\\s]+)*[^\\s]*(.[^\\s]*)*.?[^\\s]+"
    }
  }
}

=== Aresh-P/tapp/data/2015-08_F15-talks.json
{
  "name" : "Fall 2015",
  "slug" : "fall15",
  "first_date" : "2015-09-02",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Wean 5415",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>DEVOPS!  Hippest of buzzwords, earner of thousands!  Learn to harness the immense power of devops for yourself, by coming to the Fall 2015 Computer Club Workshop/Talk Series.  We will tell you the tricks that will allow you to transcend the annoyances of administration and offenses of operations, and return to the elegant, pure simplicity of raw code!</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to talks@club.</p>",
  "categories" : [
    "Power Tools",
    "Retro",
    "Dev Tools",
    "Security",
    "Languages"
  ],
  "talks" : [
    {
      "title" : "Power Computing at CMU",
      "cat" : 1,
      "notes" : "power-computing.html",
      "desc" : "CMU is the top computer science university in the world. So obviously there are some useful software tools here, available to you! Learn what they are and how to use them to get your work done faster and more efficiently."
    },
    {
      "title" : "Source Version Control with Git",
      "cat" : 1,
      "notes" : "power-git.html",
      "location" : "Wean 5409",
      "desc" : "Do you like having undo and redo available in your editor? Then you're sure to like having undo and redo available on the command line! In this talk, you'll learn about the ideas behind the source version control system Git, and how to use its immense power for your own aims."
    },
    {
      "title" : "Power Vim",
      "cat" : 1,
      "notes" : "power-vim.html",
      "desc" : "Attend this talk to learn how to efficiently use the most powerful editor on earth! Even if you use an inferior editor, come to this talk! You might find you'd prefer this one!"
    },
    {
      "title" : "Power Emacs",
      "cat" : 1,
      "notes" : "power-emacs.html",
      "desc" : "Attend this talk to learn how to efficiently use the most powerful editor on earth! Even if you use an inferior editor, come to this talk! You might find you'd prefer this one!"
    },
    {
      "title" : "(TOC Week)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "Early Home Computers and Video Games",
      "cat" : 2,
      "notes" : "early-games.html",
      "desc" : "Did people use computers before Windows? They sure did.  Was there life on the Internet before Facebook and YouTube?  Certainly.  Did people play video games before Nintendo?  Absolutely.  From the machine room and arcade to the living room, attend this talk to learn about home computers and video games that your parents grew up with."
    },
    {
      "title" : "History of Video Games: Nintendo",
      "cat" : 2,
      "notes" : "nintendo.html",
      "desc" : "Nintendo dominated the video game business in the 1980s and early 1990s.  Come learn about the history of the Nintendo Entertainment System and Super Nintendo, as well as the technology behind these consoles."
    },
    {
      "title" : "History of Video Games: Sega",
      "cat" : 2,
      "notes" : "sega.html",
      "desc" : "Before becoming a third-party software publisher, Sega was once a thriving hardware company with a 60% market share and some of the most innovative designs on the market. Come learn about Sega's past, their cool consoles, and some games you might not have heard of."
    },
    {
      "title" : "Embedded Systems and Microcontrollers",
      "cat" : 3,
      "notes" : "embedded.html",
      "desc" : "There are computers all around us in today's technology, but they aren't what most people think of as computers. Welcome to the world of embedded computing and microcontrollers! A brief overview from the popular 8-bit Arduino up to the 32-bit x86 Intel Edison."
    },
    {
      "title" : "Thermonuclear Emacs",
      "cat" : 3,
      "notes" : "thermonuclear-emacs.html",
      "desc" : "People jokingly call Emacs an operating system, but it's funny because it's true. At this talk we will explore several powerful features of Emacs that will make your life easier and let you unbind C-x C-c forever. We will cover shells, file searching, Git, themes, auto-completion, and more."
    },
    {
      "title" : "OpenSSL",
      "cat" : 4,
      "notes" : "openssl.html",
      "desc" : "What actually happens when you visit a web site with https?  Come find out about the technology behind SSL/TLS."
    },
    {
      "title" : "Wireless Networking",
      "cat" : 4,
      "notes" : "wireless-networking.html",
      "desc" : "802.11 wireless networking is widely used.  Come find out how this works, and how it is (or sometimes isn't) secured."
    },
    {
      "title" : "(Thanksgiving)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "Memory Safety in Rust",
      "cat" : 5,
      "notes" : "rust.html",
      "desc" : "Rust, a new systems programming language from Mozilla, uses novel concepts of ownership, borrowing, and lifetimes to ensure static memory safety with no runtime overhead.  Learn how the compiler can replace the garbage collector with the imposition of new language semantics."
    },
    {
      "title" : "Firewalling with OpenBSD's PF packet filter",
      "cat" : 5,
      "notes" : "firewalling-pf.html",
      "desc" : "OpenBSD is a UNIX-like operating system descended from Berkeley Software Distribution (BSD), a Research Unix derivative developed at the University of California, Berkeley. It was forked from NetBSD by project leader Theo de Raadt in late 1995.  PF is a BSD licensed stateful packet filter developed for OpenBSD as a replacement for Darren Reed's IPFilter.  In this short presentation we will do a hands on OpenBSD installation and basic configuration of PF software which will enable us to identify and block network traffic which we do not want to let into our local network or let out to the world outside."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "assets/ghs_logo.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2015-01_S15-talks-part1.json
{
  "name" : "Spring 2015",
  "slug" : "spring15",
  "first_date" : "2015-01-21",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Gates 4301",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>Want to learn more about practical aspects of computer engineering, ranging from command line usage to webapp deployment? Come to Computer Club's Spring 2015 weekly talk series! This semester, we will discuss topics ranging from command line workflows to Node.js.  <b>More talks will be added soon!</b></p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to operations@club.</p>",
  "categories" : [
    "Hacky Things!",
    "Web Applications"
  ],
  "talks" : [
    {
      "title" : "Useful Command Line Workflows",
      "cat" : 1,
      "notes" : "command-line.html",
      "desc" : "Use the command line now and then, but find it to be tedious and painful? Just want to sharpen your skills and efficiency with command-line use?  In this talk, we will present several slick workflows which allow you to accomplish tasks quickly and efficiently from the command line, from grabbing videos off of YouTube from easily switching between running, compiling, and testing your code."
    },
    {
      "title" : "Elliptic Curve Cryptography",
      "cat" : 1,
      "notes" : "ecc.pdf",
      "desc" : "Modern cryptography uses elliptic curves.  What is an elliptic curve, and why is it useful for cryptography?  And what does this have to do with ellipses, anyway?  Come find out."
    },
    {
      "title" : "Introduction to Bitcoin",
      "cat" : 1,
      "notes" : "bitcoin.html",
      "desc" : "Bitcoin is the application of cryptography to electronic money.  Come learn how to get started with bitcoin."
    },
    {
      "title" : "Docker and Fig 101",
      "cat" : 2,
      "notes" : "docker-and-fig.html",
      "desc" : "Docker and Fig are cool technologies that allow you to compartmentalize your production workflow in any language.  However, we'll discuss how we can use these technologies to improve your development cycle, as well!  While we'll be \"Dockerizing\" a Node.js application, the lessons are applicable to all of the main web development platforms.  A basic background with webapps is helpful, but not necessary.  No Docker experience needed."
    },
    {
      "title" : "Coffeescript 101",
      "cat" : 2,
      "notes" : "coffeescript.html",
      "desc" : "Check out the language sensation sweeping the nation!  Not really, but Coffeescript is a good way to dramatically increase legibility, avoid some Javascript pitfalls, and otherwise make developing on the client and server easier.  We'll open with a discussion of Coffee syntax and set up of the development platform, then run through applying it to the client with JQuery, and on the server with Node.js.  JavaScript syntax background is needed."
    },
    {
      "title" : "Vim as an IDE",
      "cat" : 2,
      "notes" : "vim.html",
      "desc" : "Vim was designed for the advanced user, and advanced users like complete control over their environment. To fulfill this requirement, Vim comes completely unconfigured--it's a blank slate. The problem is, not everyone's an advanced user! An unconfigured Vim is all but unusable. As it turns out, configuring Vim is very straightforward! In this talk, we'll introduce you to Vim plugins using the plugin manager Vundle. Our goal will be to walk out with a fully configured Vim setup. This includes a pleasant color scheme, fancy status bar indicators, code-aware features, Git integration, and more! Vim has a solution to handle just about anything that a normal IDE would. It's just about knowing where to start."
    },
    {
      "title" : "Node.js 101",
      "cat" : 2,
      "notes" : "node-js.html",
      "desc" : "This is an introduction to the hot new server paradigm of Node.js.  We'll briefly go over how Node.js is different from other platforms like Rails and Django (besides using JavaScript) and when it's best to use it.  Then we'll dive in to using Express and Mongo with Jade templating to make a MEN stack application.  When you leave, you should be able to build your own web-apps in Node.js.  Background in JavaScript syntax is helpful, but not necessary.  No web-app experience neeeded."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "ghlogos/GHS_Logo.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2016-09_F16-talks.json
{
  "name" : "Fall 2016",
  "slug" : "fall16",
  "first_date" : "2016-09-07",
  "start_time" : "20:00",
  "end_time" : "21:00",
  "location" : "Wean 5415",
  "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
  "web_desc" : "<p>DEVOPS! Hippest of buzzwords, earner of thousands! Learn to harness the immense power of devops for yourself, by coming to the Fall 2016 Computer Club Workshop/Talk Series. We will tell you the tricks that will allow you to transcend the annoyances of administration and offenses of operations, and return to the elegant, pure simplicity of raw code!</p>",
  "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to talks@club.</p>",
  "talks" : [
    {
      "title" : "Power Computing at CMU",
      "cat" : 1,
      "notes" : "power-computing.html",
      "desc" : "CMU is the top computer science university in the world. So obviously there are some useful software tools here, available to you! Learn what they are and how to use them to get your work done faster and more efficiently."
    },
    {
      "title" : "Choosing a Text Editor That's Right for You",
      "cat" : 1,
      "notes" : "editors.html",
      "desc" : "Attend this talk to learn how to use the most powerful editor on earth, as well as two more that are slightly inferior! (Which is which is up to you!) Learn about modal, chordal, and graphical ways of efficiently editing text with Vim, Emacs, and Sublime."
    },
    {
      "title" : "Computer Graphics Demo Screenings",
      "cat" : 2,
      "notes" : "demo-screenings.html",
      "desc" : "Help us select computer graphic demos to screen at Demosplash, our annual demoparty that's the largest on the east coast!"
    },
    {
      "title" : "Source Version Control with Git",
      "cat" : 1,
      "notes" : "git.html",
      "desc" : "Do you like having undo and redo available in your editor? Then you're sure to like having undo and redo available on the command line! In this talk, you'll learn about the ideas behind the source version control system Git, and how to use its immense power for your own aims."
    },
    {
      "title" : "\"Professors and Pizza\"",
      "cat" : 3,
      "notes" : "profs-and-pizza-1.html",
      "desc" : "TBD."
    },
    {
      "title" : "How Deep Learning Works",
      "cat" : 4,
      "notes" : "deep-learning.pdf",
      "desc" : "Computers have been using logic since they were first invented... but now they seem to be \"thinking\" intuitively. The technology behind computers playing games of Go, recognizing objects, and stylizing photographs is \"Deep Learning\". This branch of Machine Learning uses Artificial Neural Networks for many tasks, so let's take a look at how they work."
    },
    {
      "title" : "The Math of RSA Public-Key Crypto",
      "cat" : 4,
      "notes" : "rsa.pdf",
      "desc" : "RSA is widely used to secure communications on the Internet. Join us for some history about Rivest, Shamir, and Aldeman, the company they founded, and an explanation of the math behind this form of public-key cryptography."
    },
    {
      "title" : "Early Home Computers and Video Games",
      "cat" : 4,
      "notes" : "early-home-computing.pdf",
      "desc" : "Did people use computers before Windows? They sure did. Was there life on the Internet before Facebook and YouTube? Certainly. Did people play video games before Nintendo? Absolutely. From the machine room and arcade to the living room, attend this talk to learn about home computers and video games that your parents grew up with."
    },
    {
      "title" : "\"Professors and Pizza\"",
      "cat" : 3,
      "notes" : "profs-and-pizza-2.html",
      "desc" : "TBD."
    },
    {
      "title" : "iOS Development for the Frightened",
      "cat" : 5,
      "notes" : "ios-dev.pdf",
      "desc" : "Want to begin developing for iOS? This workshop will cover the basics of iOS development including using Xcode, Swift, the Interface builder as well as the many other developer tools available to you. No experience in iOS or Swift is required."
    },
    {
      "title" : "The Dot Com Bubble",
      "cat" : 5,
      "notes" : "dot-com.pdf",
      "desc" : "In the late 1990s, the Internet appeared to be a never-ending sea of free money. Tech stocks were all the rage, and anything with \".com\" in the name was a guaranteed moneymaker. But it was not to last. Many entrepreneurs lost their fortunes overnight, and \".com\" went from being a buzzword to a swear word. In this talk we'll discuss the Internet bubble, and how you can avoid making some of the same mistakes."
    },
    {
      "title" : "(Thanksgiving)",
      "cat" : 0,
      "notes" : "",
      "desc" : ""
    },
    {
      "title" : "How Super are Supercomputers?",
      "cat" : 5,
      "notes" : "supercomputing.pdf",
      "desc" : "In the early 2000s, computers stopped getting faster. Today, computer processors improve mainly by adding more cores, while each one runs at the same speed. Developing efficient software in this new phase of Moore's Law requires different techniques... but supercomputers have had hundreds and thousands of processors for many decades now, so how did they work?"
    },
    {
      "title" : "\"Professors and Pizza\"",
      "cat" : 3,
      "notes" : "profs-and-pizza-3.html",
      "desc" : "TBD."
    }
  ],
  "url" : "http://www.cmucc.org/talks",
  "sponsor" : {
    "name" : "Green Hills Software",
    "url" : "http://www.ghs.com",
    "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
    "logo" : "assets/ghs_logo.svg",
    "logo_svg-gen_height_offset" : 48
  }
}

=== Aresh-P/tapp/data/2017-02_S17-talks.json
{
 "name" : "Spring 2017",
 "slug" : "spring17",
 "first_date" : "2017-02-08",
 "start_time" : "20:00",
 "end_time" : "21:00",
 "location" : "Wean 5403",
 "ical_desc" : "A series of talks and workshops on some of the most useful tools for advanced users and developers led by the Carnegie Mellon University Computer Club.",
 "web_desc" : "<p>DEVOPS! Hippest of buzzwords, earner of thousands! Learn to harness the immense power of devops for yourself, by coming to the Spring 2017 Computer Club Workshop/Talk Series. We will tell you the tricks that will allow you to transcend the annoyances of administration and offenses of operations, and return to the elegant, pure simplicity of raw code!</p>",
 "web_suggest" : "<p>If you would like to request, propose, or volunteer a talk, join us on IRC or email your talk idea to talks@club.</p>",
 "talks" : [
  {
   "title" : "Debugging with GDB",
   "cat" : 1,
   "notes" : "gdb.tar.gz",
   "desc" : "Tired of spending hours staring at your code while trying to diagnose mysterious segfaults? This talk will teach you how to use GDB, a powerful debugging tool with the ability to help you find out exactly what's wrong with your code."
  },
  {
   "title" : "sed & awk: '70s tools still hip today",
   "cat" : 1,
   "notes" : "sed-and-awk.html",
   "desc" : "Providing much of the meat and bones of shell scripting, sed and awk process line-based data into more useful information. This talk will convey how to use these classic tools from the early days of UNIX to do what you need, and how they have influenced other languages."
  },
  {
   "title" : "Using Windows at CMU",
   "cat" : 1,
   "notes" : "windows.html",
   "desc" : "Microsoft Windows is a very common OS platform. However, computer science at CMU is taught almost entirely in UNIX. Learn about a few tools you can use to interface with Linux. Learn about ways to program for portability and their limitations. Also learn some Windows shortcuts."
  },
  {
   "title" : "Burroughs MCP (not the evil one from Tron)",
   "cat" : 2,
   "notes" : "burroughs-mcp.html",
   "desc" : "The Burroughs large systems and their operating sytstem (MCP) pioneered many features that we take for granted including virtual memory, multitasking, the NX-bit, and an OS written in a higher level language ... all back in the 1960s! They also had many features which modern systems lack, such as hardware enforced type safety and immunity to buffer overflows. This talk will explain all the above and more."
  },
  {
   "title" : "Programming in Rust: Speed meets safety",
   "cat" : 3,
   "notes" : "rust.html",
   "desc" : "Writing software is dangerous work. Race conditions, buffer overflows, and memory corruption can all compromise the functionality and security of programs that you write. Some languages eliminate these errors at the cost of performance, but is there a way to get the best of both worlds? Rust brings together the speed of C, the usability of Python, and the provable safety of Haskell, in one well-engineered programming language."
  },
  {
   "title" : "(Spring Break)",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "An introduction to LaTeX",
   "cat" : 3,
   "notes" : "latex.html",
   "desc" : "LaTeX is a convenient, customizable, and Turing-complete (!) way to typeset technical documents, homework, and more. This talk is intended to be a basic primer on setting up and making use of the basic features of LaTeX."
  },
  {
   "title" : "Escaping reality: VR from sci-fi to practice",
   "cat" : 4,
   "notes" : "vr.html",
   "desc" : "Virtual Reality was once a wild dream, existing only in science fiction novels. Now it has become more than real. From Ivan Sutherland's \"Sword of Damocles\" to the HTC Vive, this talk will cover a brief history of VR, some of the more fascinating aspects of the rendering pipeline involved, and an overview of the current trends in the industry."
  },
  {
   "title" : "Strange and quirky CPU architectures",
   "cat" : 4,
   "notes" : "arch-quirks.html",
   "desc" : "Throughout history, engineers have explored a variety of novel CPU designs in a quest for better performance. This talk will explore some of the more interesting attempts at processor architecture."
  },
  {
   "title" : "Modern CPU architectures and instruction sets",
   "cat" : 4,
   "notes" : "arch-modern.html",
   "desc" : "Modern computing devices use a variety of CPU architectures, including x86, ARM, and MIPS. This talk explains the origins and differences in the design and instruction sets of the processors found in modern desktops, laptops, phones, and embedded systems."
  },
  {
   "title" : "(Carnival Eve)",
   "cat" : 0,
   "notes" : "",
   "desc" : ""
  },
  {
   "title" : "Attack of the Clones: Apple II's many imitators",
   "cat" : 5,
   "notes" : "apple-ii-clones.html",
   "desc" : "The massive popularity of the Apple II inspired scores of imitations abroad, from Australia to Brazil to the USSR. Apple did not take kindly to the knockoffs. This talk explores the most interesting of the clones, Apple's response, and what happened to manufacturers who made legally-questionable tributes to the famous machine."
  },
  {
   "title" : "NeXTStep: Mac OS X's CMU connection",
   "cat" : 5,
   "notes" : "nextstep.html",
   "desc" : "In 1998, Apple Computer acquired NeXT, a near-bankrupt former workstation vendor. Why would they do this? Simple, Apple needed a better OS and NeXT had it. This talk explores the history of OS X and NeXTStep, and its basis in research developed at CMU."
  }
 ],
 "url" : "http://www.cmucc.org/talks",
 "sponsor" : {
  "name" : "Green Hills Software",
  "url" : "http://www.ghs.com",
  "desc" : "Green Hills make the world's highest performing compilers, most secure real-time operating systems, revolutionary debuggers, and virtualization solutions for embedded systems.",
  "logo" : "assets/ghs_logo.svg",
  "logo_svg-gen_height_offset" : 48
 }
}
